### ISSUE TITLE
Ask for help about the access of processed data

### ISSUE THREAD

**Issue by MaoAiBio** [quadratolab/Cerebellar-Organoid-2023#1]
Dear Professor,

I recently read the paper "Human cerebellar organoids with functional Purkinje cells" published by your laboratory. This paper innovatively introduces Purkinje cells into the brain. This gave me great inspiration and help with my research topic. However, it seems that I did not find the cell annotation information about the original figure1F. Can you provide me with a copy for reference?

Looking forward to hearing from you

Hanwen

**Comment by quadratolab** [comment]
Hi Hanwen,

After integrating the fetal and organoid data sets, we used coclustering with fetal and known cell-type markers to assign/annotate each cell with a label/meta identity in the script named: "classify.D2.Aldinger.manuscript".  However, I will try to upload the meta.data of the final object. (hopefully by next week :)

Tuan/JoJo

**Comment by MaoAiBio** [comment]
> Hi Hanwen,
> 
> After integrating the fetal and organoid data sets, we used coclustering with fetal and known cell-type markers to assign/annotate each cell with a label/meta identity in the script named: "classify.D2.Aldinger.manuscript". However, I will try to upload the meta.data of the final object. (hopefully by next week :)
> 
> Tuan/JoJo

Hi Tuan/JoJo,

Thank you very much for your reply.

Considering that this study performed three single-cell sequencing (D1, D2 and D3), if the three types of data are combined, there may be barcode overlap. Can you share a copy of the count data and cell metadata? This will greatly help us understand this data.

Hanwen

**Comment by quadratolab** [comment]
I have uploaded the metadata for the both the organoid and fetal data at the GEO site. 

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE247974
